### ISSUE TITLE
Learning - Information Engineering(Rajeswari)

### ISSUE THREAD

**Issue by ExternshipSAG** [externship-sag/RSATeam1#14]
Complete the Following Courses 
Udemy Course
1.Technical Writers Master Class
2.DITA 

Free Courses
Allsion - Technical Writing Essential Training
Allsion - Improve Writing Skills

Webinar
DITA

Take English Grammar Test

**Comment by SunshineVenus** [comment]
19/7/22 - Installed Oxygen editor and practised DITA
