### ISSUE TITLE
RSA - Test Design for Feature 2 (Silpa)

### ISSUE THREAD

**Issue by Pavithra-Kayal** [externship-sag/RSATeam1#28]
- [ ] Understand the feature
- [ ]  Derive Testcases
- [ ]  Review

09-08-2022

Pulled the latest code
Did the testing with the latest code and found some defects
Reviewed Vaibhavi's test case

12-08-2022

Pulled the latest code and did the testing

**Comment by SilpaMadhu** [comment]
[Feature2 TestCases.xlsx](https://github.com/externship-sag/RSATeam1/files/9316096/Feature2.TestCases.xlsx)
