### ISSUE TITLE
Testcase Design (Gayatri)

### ISSUE THREAD

**Issue by Gayatrivl** [externship-sag/RSATeam1#6]
Acceptance Criteria

- [x]  What is Testcase Design
- [x]  How to write Testcases?
- [ ] Gmail Login Page: Derive Testcases
- [ ] Derive Testcases for RSA - Feature 12
- [ ] Derive Testcases for RSA - Feature

@geka001

-[ 04/07/2022] -

 Learning Git/Github

[05/07/2022]

Test Cases design     
      - Attended Testcase design techniques session.
      - Read about test case design techniques
      - Designing test cases for Gmail login page.

[06/07/2022]
- Updated testcases as per the review comments by Meha.
- Will start with the Udemy course on manual testing and Java Cucumber course.

[07/07/2022]-
Started with the Udemy course on manual testing - Software testing with Jira and Agile,

08-07-2022

Continued learning Udemy course on Software Testing with Jira and Agile

11-12-2022

*Continued learning Udemy course on Software Testing with Jira and Agile
Discussion and understanding of the new feature - Resume Screening.

12-12-2022

Studied Design document of the Resume Screening feature.
Started writing test cases for RSA Feature.
Started with Udemy course on Java Selenium Cucumber Framework - https://www.udemy.com/course/cucumber-tutorial/

13/07/2022

Had a sync up with the buddy
Attended the session 'Types of Testing' by Vijeta
Worked on the test cases for the Resume Screening Application
Reviewed Pavithra's test case for resume screening

14/07/2022

Attended the session - 'success story of Richa'
Took session on Encryption to the team.
Attended the session on 'Cucumber-Java-Selenium Overview' by Sushant

Worked on the Resume Screening Application test cases and uploaded in GitHub
Reviewed Pavithra's test cases

[Testcases_ResumeScreening.xlsx](https://github.com/externship-sag/RSATeam1/files/9114343/Testcases_ResumeScreening.xlsx)

**Comment by Gayatrivl** [comment]
Testcases...

[Testcases_gmail_Gayatri.xlsx](https://github.com/externship-sag/RSATeam1/files/9051240/Testcases_gmail_Gayatri.xlsx)

**Comment by mehamahajan** [comment]
Comments 06/07
1)Add positive and negative cases for login by phone number
2) Add case for password lock
3)Add case for upper and lower case

**Comment by Gayatrivl** [comment]
Updated test cases
